"""empty message

Revision ID: a11f3ecc2e4b
Revises: 4ed1d89ad174
Create Date: 2019-09-09 10:05:15.071240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a11f3ecc2e4b'
down_revision = '4ed1d89ad174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('height', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'height')
    # ### end Alembic commands ###
